
#ifndef _RESOURCE_INCLUDED
#define _RESOURCE_INCLUDED

extern char _PIC_dummy[];
extern unsigned char PAL_GAME[];
extern unsigned char SHP_PLAY_A[],SHP_PLAY_N[];
extern unsigned char SHP_CREDIT_A[],SHP_CREDIT_N[];
extern unsigned char SHP_EXIT_A[],SHP_EXIT_N[];

extern unsigned char SHP_TANK_U[];
extern unsigned char SHP_TANK_D[];
extern unsigned char SHP_TANK_L[];
extern unsigned char SHP_TANK_R[];

extern unsigned char SHP_FBLOCK[],SHP_FLAG[];

extern unsigned char SHP_BULET_U[];
extern unsigned char SHP_BULET_D[];
extern unsigned char SHP_BULET_L[];
extern unsigned char SHP_BULET_R[];

extern unsigned char SHP_MY_TANK_U[];
extern unsigned char SHP_MY_TANK_D[];
extern unsigned char SHP_MY_TANK_L[];
extern unsigned char SHP_MY_TANK_R[];


#endif
